"""Realistic mock data for HR and Finance tools."""

EMPLOYEES = {
    "EMP001": {
        "id": "EMP001",
        "name": "Alice Chen",
        "email": "alice.chen@acmecorp.com",
        "department": "Engineering",
        "title": "Senior Software Engineer",
        "salary": 185000,
        "start_date": "2021-03-15",
        "manager": "EMP005",
    },
    "EMP002": {
        "id": "EMP002",
        "name": "Bob Martinez",
        "email": "bob.martinez@acmecorp.com",
        "department": "Marketing",
        "title": "Marketing Manager",
        "salary": 142000,
        "start_date": "2020-07-01",
        "manager": "EMP006",
    },
    "EMP003": {
        "id": "EMP003",
        "name": "Carol Johnson",
        "email": "carol.johnson@acmecorp.com",
        "department": "Finance",
        "title": "Financial Analyst",
        "salary": 128000,
        "start_date": "2022-01-10",
        "manager": "EMP006",
    },
    "EMP004": {
        "id": "EMP004",
        "name": "David Kim",
        "email": "david.kim@acmecorp.com",
        "department": "Engineering",
        "title": "DevOps Engineer",
        "salary": 165000,
        "start_date": "2021-09-20",
        "manager": "EMP005",
    },
    "EMP005": {
        "id": "EMP005",
        "name": "Eva Rodriguez",
        "email": "eva.rodriguez@acmecorp.com",
        "department": "Engineering",
        "title": "VP of Engineering",
        "salary": 245000,
        "start_date": "2019-04-01",
        "manager": None,
    },
    "EMP006": {
        "id": "EMP006",
        "name": "Frank O'Brien",
        "email": "frank.obrien@acmecorp.com",
        "department": "Operations",
        "title": "COO",
        "salary": 275000,
        "start_date": "2018-11-15",
        "manager": None,
    },
}

DEPARTMENTS = [
    {"name": "Engineering", "head": "EMP005", "headcount": 24, "budget_code": "ENG-2024"},
    {"name": "Marketing", "head": "EMP002", "headcount": 12, "budget_code": "MKT-2024"},
    {"name": "Finance", "head": "EMP003", "headcount": 8, "budget_code": "FIN-2024"},
    {"name": "Operations", "head": "EMP006", "headcount": 15, "budget_code": "OPS-2024"},
    {"name": "Sales", "head": None, "headcount": 20, "budget_code": "SAL-2024"},
]

BUDGETS = {
    "ENG-2024": {
        "department": "Engineering",
        "fiscal_year": 2024,
        "total_budget": 4500000,
        "spent": 3200000,
        "remaining": 1300000,
        "categories": {
            "salaries": 3000000,
            "tools_and_licenses": 350000,
            "training": 150000,
            "infrastructure": 700000,
            "travel": 100000,
            "misc": 200000,
        },
    },
    "MKT-2024": {
        "department": "Marketing",
        "fiscal_year": 2024,
        "total_budget": 2800000,
        "spent": 1900000,
        "remaining": 900000,
        "categories": {
            "salaries": 1500000,
            "advertising": 800000,
            "events": 300000,
            "tools_and_licenses": 100000,
            "travel": 100000,
        },
    },
    "FIN-2024": {
        "department": "Finance",
        "fiscal_year": 2024,
        "total_budget": 1800000,
        "spent": 1100000,
        "remaining": 700000,
        "categories": {
            "salaries": 1200000,
            "audit_services": 300000,
            "tools_and_licenses": 150000,
            "training": 75000,
            "misc": 75000,
        },
    },
}

EXPENSES = [
    {
        "id": "EXP001",
        "submitted_by": "EMP001",
        "department": "Engineering",
        "amount": 2500.00,
        "description": "AWS Summit conference registration + travel",
        "category": "travel",
        "status": "approved",
        "date": "2024-06-15",
    },
    {
        "id": "EXP002",
        "submitted_by": "EMP002",
        "department": "Marketing",
        "amount": 15000.00,
        "description": "Q3 social media ad campaign - LinkedIn",
        "category": "advertising",
        "status": "pending",
        "date": "2024-07-01",
    },
    {
        "id": "EXP003",
        "submitted_by": "EMP004",
        "department": "Engineering",
        "amount": 8400.00,
        "description": "Annual Datadog enterprise license renewal",
        "category": "tools_and_licenses",
        "status": "approved",
        "date": "2024-06-28",
    },
    {
        "id": "EXP004",
        "submitted_by": "EMP003",
        "department": "Finance",
        "amount": 45000.00,
        "description": "External audit services - Q2 review",
        "category": "audit_services",
        "status": "pending",
        "date": "2024-07-05",
    },
    {
        "id": "EXP005",
        "submitted_by": "EMP001",
        "department": "Engineering",
        "amount": 1200.00,
        "description": "Team offsite lunch + activities",
        "category": "misc",
        "status": "approved",
        "date": "2024-06-20",
    },
]

PENDING_PAYMENTS = [
    {
        "id": "PAY001",
        "vendor": "Amazon Web Services",
        "amount": 87500.00,
        "description": "Monthly infrastructure invoice - June 2024",
        "department": "Engineering",
        "due_date": "2024-07-15",
        "status": "pending_approval",
    },
    {
        "id": "PAY002",
        "vendor": "LinkedIn Advertising",
        "amount": 15000.00,
        "description": "Q3 campaign payment",
        "department": "Marketing",
        "due_date": "2024-07-10",
        "status": "pending_approval",
    },
    {
        "id": "PAY003",
        "vendor": "Deloitte & Touche",
        "amount": 45000.00,
        "description": "Q2 external audit services",
        "department": "Finance",
        "due_date": "2024-07-20",
        "status": "pending_approval",
    },
]
