#!/usr/bin/env bash
# Restore configs from configs/local/ for repeat use.
# If no saved configs exist, walks the user through initial setup.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ ! -f "$DIR/configs/local/quickstart.conf" ]; then
    echo "No saved configs found. Running first-time setup..."
    echo ""
    echo "You'll need these from Duo Admin Panel:"
    echo "  - MCP OIDC integration: OAuth URLs, Agent Client ID + Secret"
    echo "  - agentgateway integration: API hostname, Integration key, Secret key"
    echo "  - A Cloudflare tunnel URL (run: cloudflared tunnel --url http://localhost:3000)"
    echo ""
    read -rp "Press Enter when ready, or Ctrl+C to exit..."
    echo ""

    # Collect values
    echo "─── Cloudflare Tunnel ───"
    read -rp "Tunnel URL (e.g. https://random-words.trycloudflare.com): " TUNNEL_URL
    GATEWAY_URL="${TUNNEL_URL}/mcp"
    echo ""

    echo "─── Duo MCP OIDC Integration (General tab) ───"
    read -rp "OAuth Authorize URL: " OAUTH_AUTHORIZE_URL
    read -rp "OAuth Token URL: " OAUTH_TOKEN_URL
    echo ""

    echo "─── Agent Client (Clients tab → your agent client, NOT the admin panel one) ───"
    read -rp "Agent Client ID: " OAUTH_CLIENT_ID
    read -rsp "Agent Client Secret: " OAUTH_CLIENT_SECRET
    echo ""
    echo ""

    echo "─── MCPGW Tool List Client ID (for admin panel, Clients tab → first client) ───"
    read -rp "Admin Panel Client ID: " ADMIN_PANEL_CLIENT_ID
    echo ""

    echo "─── agentgateway Integration (Details section) ───"
    read -rp "API Hostname: " DUO_API_HOSTNAME
    read -rp "Integration Key: " DUO_INTEGRATION_KEY
    read -rsp "Secret Key: " DUO_SECRET_KEY
    echo ""
    echo ""

    # Derive issuer from token URL (remove /token)
    OAUTH_ISSUER="${OAUTH_TOKEN_URL%/token}"

    # Write .env
    cat > "$DIR/.env" << EOF
# Generated by restore-configs.sh on $(date -Iseconds)

OAUTH_AUTHORIZE_URL=${OAUTH_AUTHORIZE_URL}
OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
OAUTH_SCOPE=openid
OAUTH_REDIRECT_PORT=8085

DUO_API_HOSTNAME=${DUO_API_HOSTNAME}
DUO_INTEGRATION_KEY=${DUO_INTEGRATION_KEY}

AGENTGATEWAY_IMAGE=cr.agentgateway.dev/agentgateway:0.12.0
AUTHZ_CONNECTOR_IMAGE=duosecurity/authorization-connector:v1.0.0

GATEWAY_URL=${GATEWAY_URL}
EOF

    # Write quickstart.conf
    cat > "$DIR/quickstart.conf" << EOF
gateway:
  url: "http://localhost:3000/mcp"
  external_url: "${GATEWAY_URL}"

  tls:

upstreams:
  - name: acme-tools
    url: "http://mcp-server:8000/sse"

oauth:
  issuer: "${OAUTH_ISSUER}"
  admin_panel_client_id: "${ADMIN_PANEL_CLIENT_ID}"

duo:
  host: "${DUO_API_HOSTNAME}"
  integration_key: "${DUO_INTEGRATION_KEY}"
  secret_key_file: "/run/secrets/duo_skey"
  timeout: 30
  insecure_skip_verify: false

authz_bridge:
  host: "authz-bridge:9001"
  address: ":9001"
  timeout: "10s"
  tls:
    enabled: false
EOF

    # Write secret key
    mkdir -p "$DIR/secrets"
    echo -n "$DUO_SECRET_KEY" > "$DIR/secrets/duo_skey"
    chmod 600 "$DIR/secrets/duo_skey"

    # Save copies for next time
    mkdir -p "$DIR/configs/local"
    cp "$DIR/quickstart.conf" "$DIR/configs/local/quickstart.conf"
    cp "$DIR/.env" "$DIR/configs/local/.env"
    cp "$DIR/secrets/duo_skey" "$DIR/configs/local/duo_skey"

    echo ""
    echo "✓ All configs generated and saved to configs/local/"
    echo "✓ Run: COMPOSE_PROFILES=agentgateway docker compose up -d"
    echo ""
    echo "Don't forget to set in Duo Admin Panel:"
    echo "  - MCP OIDC → Resource URLs: ${GATEWAY_URL}"
    echo "  - agentgateway → agentgateway URLs: ${GATEWAY_URL}"
    exit 0
fi

# ─── Configs exist: restore them ───

cp "$DIR/configs/local/quickstart.conf" "$DIR/quickstart.conf"
cp "$DIR/configs/local/.env" "$DIR/.env"
mkdir -p "$DIR/secrets"
cp "$DIR/configs/local/duo_skey" "$DIR/secrets/duo_skey"
chmod 600 "$DIR/secrets/duo_skey"

echo "✓ Configs restored from configs/local/"
echo ""

# Check if tunnel URL needs updating
CURRENT_URL=$(grep "GATEWAY_URL" "$DIR/.env" | cut -d= -f2)
echo "Current tunnel URL: $CURRENT_URL"
echo ""
read -rp "Is the tunnel URL still correct? (y/N): " CORRECT

if [[ "$CORRECT" != "y" && "$CORRECT" != "Y" ]]; then
    read -rp "New tunnel URL (e.g. https://new-words.trycloudflare.com): " NEW_TUNNEL
    NEW_GATEWAY="${NEW_TUNNEL}/mcp"

    # Update .env
    sed -i '' "s|GATEWAY_URL=.*|GATEWAY_URL=${NEW_GATEWAY}|" "$DIR/.env"

    # Update quickstart.conf
    sed -i '' "s|external_url:.*|external_url: \"${NEW_GATEWAY}\"|" "$DIR/quickstart.conf"

    # Save updated copies
    cp "$DIR/quickstart.conf" "$DIR/configs/local/quickstart.conf"
    cp "$DIR/.env" "$DIR/configs/local/.env"

    echo ""
    echo "✓ Updated tunnel URL to: ${NEW_GATEWAY}"
    echo ""
    echo "⚠  Also update in Duo Admin Panel:"
    echo "  1. MCP OIDC integration → General → Resource URLs"
    echo "  2. agentgateway integration → agentgateway URLs"
    echo ""
    echo "Then restart: docker compose down && COMPOSE_PROFILES=agentgateway docker compose up -d"
else
    echo ""
    echo "✓ Ready. Run: COMPOSE_PROFILES=agentgateway docker compose up -d"
fi
