#!/usr/bin/env bash
# Restore configs and start Cloudflare tunnel for the demo.
# - First-time: walks user through setup
# - Repeat use: restores saved configs, starts tunnel, shows where to update URL
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ─── Start Cloudflare tunnel in background ───
start_tunnel() {
    echo "─── Starting Cloudflare Tunnel ───"
    echo ""
    echo "⚠  NOTE: We're using a free quick tunnel. The URL changes every time."
    echo "  For a stable URL, set up a named tunnel (see README)."
    echo ""

    # Kill any existing tunnel
    pkill -f "cloudflared tunnel" 2>/dev/null || true
    sleep 1

    # Start in background, capture logs
    cloudflared tunnel --url http://localhost:3000 > /tmp/cloudflared.log 2>&1 &
    TUNNEL_PID=$!
    echo "  Tunnel starting (PID: $TUNNEL_PID)..."

    # Wait for URL to appear in logs
    for i in $(seq 1 15); do
        TUNNEL_URL=$(grep -o 'https://[a-z0-9-]*\.trycloudflare\.com' /tmp/cloudflared.log 2>/dev/null | head -1)
        if [ -n "$TUNNEL_URL" ]; then
            break
        fi
        sleep 1
    done

    if [ -z "$TUNNEL_URL" ]; then
        echo "  ✗ Could not detect tunnel URL. Check /tmp/cloudflared.log"
        echo "  You may need to run: cloudflared tunnel --url http://localhost:3000"
        exit 1
    fi

    GATEWAY_URL="${TUNNEL_URL}/mcp"
    echo ""
    echo "  ┌─────────────────────────────────────────────────────────────┐"
    echo "  │ Tunnel URL: $TUNNEL_URL"
    echo "  │ Gateway URL: $GATEWAY_URL"
    echo "  └─────────────────────────────────────────────────────────────┘"
    echo ""
    echo "  ⚠  UPDATE THESE in Duo Admin Panel:"
    echo "     1. Applications → MCP OIDC integration → General → Resource URLs"
    echo "        → set to: $GATEWAY_URL"
    echo "     2. Applications → agentgateway integration → agentgateway URLs"
    echo "        → set to: $GATEWAY_URL"
    echo ""
    read -rp "  Press Enter after updating Duo Admin (or Ctrl+C to abort)..."
    echo ""
}

# ─── First-time setup ───
first_time_setup() {
    echo "No saved configs found. Running first-time setup..."
    echo ""
    echo "You'll need these from Duo Admin Panel:"
    echo "  - MCP OIDC integration: OAuth URLs, Agent Client ID + Secret"
    echo "  - agentgateway integration: API hostname, Integration key, Secret key"
    echo ""
    read -rp "Press Enter when ready, or Ctrl+C to exit..."
    echo ""

    # Start tunnel first so we have the URL
    start_tunnel

    echo "─── Duo MCP OIDC Integration (General tab) ───"
    read -rp "OAuth Authorize URL: " OAUTH_AUTHORIZE_URL
    read -rp "OAuth Token URL: " OAUTH_TOKEN_URL
    echo ""

    echo "─── Agent Client (Clients tab → your agent client, NOT the admin panel one) ───"
    read -rp "Agent Client ID: " OAUTH_CLIENT_ID
    read -rsp "Agent Client Secret: " OAUTH_CLIENT_SECRET
    echo ""
    echo ""

    echo "─── MCPGW Tool List Client ID (Clients tab → first client) ───"
    read -rp "Admin Panel Client ID: " ADMIN_PANEL_CLIENT_ID
    echo ""

    echo "─── agentgateway Integration (Details section) ───"
    read -rp "API Hostname: " DUO_API_HOSTNAME
    read -rp "Integration Key: " DUO_INTEGRATION_KEY
    read -rsp "Secret Key: " DUO_SECRET_KEY
    echo ""
    echo ""

    # Derive issuer from token URL (remove /token)
    OAUTH_ISSUER="${OAUTH_TOKEN_URL%/token}"

    # Write .env
    cat > "$DIR/.env" << EOF
# Generated by restore-configs.sh on $(date -Iseconds)

OAUTH_AUTHORIZE_URL=${OAUTH_AUTHORIZE_URL}
OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
OAUTH_SCOPE=openid
OAUTH_REDIRECT_PORT=8085

DUO_API_HOSTNAME=${DUO_API_HOSTNAME}
DUO_INTEGRATION_KEY=${DUO_INTEGRATION_KEY}

AGENTGATEWAY_IMAGE=cr.agentgateway.dev/agentgateway:0.12.0
AUTHZ_CONNECTOR_IMAGE=duosecurity/authorization-connector:v1.0.0

GATEWAY_URL=${GATEWAY_URL}
EOF

    # Write quickstart.conf
    cat > "$DIR/quickstart.conf" << EOF
gateway:
  url: "http://localhost:3000/mcp"
  external_url: "${GATEWAY_URL}"

  tls:

upstreams:
  - name: acme-tools
    url: "http://mcp-server:8000/sse"

oauth:
  issuer: "${OAUTH_ISSUER}"
  admin_panel_client_id: "${ADMIN_PANEL_CLIENT_ID}"

duo:
  host: "${DUO_API_HOSTNAME}"
  integration_key: "${DUO_INTEGRATION_KEY}"
  secret_key_file: "/run/secrets/duo_skey"
  timeout: 30
  insecure_skip_verify: false

authz_bridge:
  host: "authz-bridge:9001"
  address: ":9001"
  timeout: "10s"
  tls:
    enabled: false
EOF

    # Write secret key
    mkdir -p "$DIR/secrets"
    echo -n "$DUO_SECRET_KEY" > "$DIR/secrets/duo_skey"
    chmod 600 "$DIR/secrets/duo_skey"

    # Save copies for next time
    mkdir -p "$DIR/configs/local"
    cp "$DIR/quickstart.conf" "$DIR/configs/local/quickstart.conf"
    cp "$DIR/.env" "$DIR/configs/local/.env"
    cp "$DIR/secrets/duo_skey" "$DIR/configs/local/duo_skey"

    echo ""
    echo "✓ All configs generated and saved to configs/local/"
    echo "✓ Run: make up"
}

# ─── Repeat use: restore and update tunnel ───
repeat_setup() {
    echo "─── Restoring saved configs ───"
    cp "$DIR/configs/local/quickstart.conf" "$DIR/quickstart.conf"
    cp "$DIR/configs/local/.env" "$DIR/.env"
    mkdir -p "$DIR/secrets"
    cp "$DIR/configs/local/duo_skey" "$DIR/secrets/duo_skey"
    chmod 600 "$DIR/secrets/duo_skey"
    echo "  ✓ Configs restored from configs/local/"
    echo ""

    # Start tunnel and get new URL
    start_tunnel

    # Update configs with new URL
    sed -i '' "s|GATEWAY_URL=.*|GATEWAY_URL=${GATEWAY_URL}|" "$DIR/.env"
    sed -i '' "s|external_url:.*|external_url: \"${GATEWAY_URL}\"|" "$DIR/quickstart.conf"

    # Save updated copies
    cp "$DIR/quickstart.conf" "$DIR/configs/local/quickstart.conf"
    cp "$DIR/.env" "$DIR/configs/local/.env"

    echo "  ✓ Configs updated with new tunnel URL"
    echo ""
    echo "  Next: make up"
}

# ─── Main ───
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   Duo Agentic Identity Demo — Setup                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

if [ -f "$DIR/configs/local/quickstart.conf" ]; then
    repeat_setup
else
    first_time_setup
fi
