#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   Duo Agentic Identity Demo — Setup                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

if [ -f "$PROJECT_DIR/.env" ]; then
    echo "⚠  .env already exists. Overwrite? (y/N)"
    read -r answer
    if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
        echo "Keeping existing .env"
        exit 0
    fi
fi

echo "─── Duo MCP OIDC Integration (Applications → MCP → General tab) ───"
echo ""
echo "You need the OAuth Token URL from the General tab. The Authorize URL"
echo "is the same base but ending in /authorize instead of /token."
echo ""
read -rp "OAuth Authorize URL: " OAUTH_AUTHORIZE_URL
read -rp "OAuth Token URL: " OAUTH_TOKEN_URL
read -rp "Client ID (from Confidential Client Registration): " OAUTH_CLIENT_ID
echo ""

echo "─── Duo agentgateway Integration (Applications → agentgateway → Details) ───"
echo ""
read -rp "API Hostname (e.g. api-xxxxxxxx.duosecurity.com): " DUO_API_HOSTNAME
read -rp "Integration Key: " DUO_INTEGRATION_KEY
read -rsp "Secret Key: " DUO_SECRET_KEY
echo ""
echo ""

echo "─── Cloudflare Tunnel ───"
read -rp "Tunnel Token: " CLOUDFLARE_TUNNEL_TOKEN
read -rp "Gateway Public URL (e.g. https://mcpgw.example.com/mcp): " GATEWAY_URL
echo ""

# Write .env
cat > "$PROJECT_DIR/.env" << EOF
# Generated by setup.sh on $(date -Iseconds)

OAUTH_AUTHORIZE_URL=${OAUTH_AUTHORIZE_URL}
OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
OAUTH_SCOPE=openid
OAUTH_REDIRECT_PORT=8085

DUO_API_HOSTNAME=${DUO_API_HOSTNAME}
DUO_INTEGRATION_KEY=${DUO_INTEGRATION_KEY}

AGENTGATEWAY_IMAGE=cr.agentgateway.dev/agentgateway:0.12.0
AUTHZ_CONNECTOR_IMAGE=duosecurity/authorization-connector:v1.0.0

CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
GATEWAY_URL=${GATEWAY_URL}
EOF

# Write secret key to file (not in .env)
mkdir -p "$PROJECT_DIR/gateway/secrets"
echo -n "$DUO_SECRET_KEY" > "$PROJECT_DIR/gateway/secrets/duo_skey"
chmod 600 "$PROJECT_DIR/gateway/secrets/duo_skey"

echo ""
echo "✓ Configuration saved to .env"
echo "✓ Secret key saved to gateway/secrets/duo_skey"
echo "✓ Run 'make up' to start services"
